modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousLights/issues"
logoFile="curiouslights_icon.png"
logoBlur=false
[[mods]]
modId="curiouslights"
version="${version}"
displayName="Curious Lights"
displayURL="https://www.curseforge.com/minecraft/mc-mods/curious-lights"
authors="C4"
description='''
A compatibility bridge between Curios API and dynamic light mods such as Dynamic Lights and Lucent.
'''
[[dependencies.curiouslights]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouslights]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouslights]]
    modId="curios"
    mandatory=true
    versionRange="[1.18-5.0.2.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouslights]]
    modId="dynamiclights"
    mandatory=false
    versionRange="[1.18.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouslights]]
    modId="dynamiclightsreforged"
    mandatory=false
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
